### ISSUE TITLE
History - Image with name are not opened with the same name

### ISSUE THREAD

**Issue by riverdiego** [Ginj-capture/Ginj#10]
I've copied an image with the name "123456789" but when i look for this image and double click on it within the History, it's opened with a different name (looks like the default "timestamp")
Repro Steps
1- Take an screenshop (capture)
2- Set a name and click on Copy button
3- Go to History and double click on it
4- Verify the name of image
Actual
Image has a default name instead of displays the name previously saved

![image](https://user-images.githubusercontent.com/22159796/88119057-b6766700-cb95-11ea-8354-edff776c9653.png)

**Comment by vicnevicne** [comment]
Indeed, that does not sound logical. I'll change that.
By the way, knowing that once you will share it again, it will create a new entry in the history (that's the way Jing worked and I think it makes sense), would you prefer the new copy to be named exactly the same, or with a "_v2" suffix (like you see above) ?

**Comment by riverdiego** [comment]
exactly, i was going to suggest that, to use the previously saved name with a "_v2"  @vicnevicne

**Comment by vicnevicne** [comment]
It's fixed in the code and will be in the next release. Don't know when it will be though...

**Comment by vicnevicne** [comment]
v0.3.6 was released and should fix the issue :-)
Closing. Don't hesitate to reopen if you have issues.
