### ISSUE TITLE
two ways to reach Target Configuration

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#16]
I'd prefer to only have one way to configuration. Now I want to upload and click by mistake the other button see picture:
![twoways](https://user-images.githubusercontent.com/6506666/88295025-2eab6c80-ccfd-11ea-9920-4d0da64ac3fc.png)

Like you suggested, a preferred upload button would be the best. I think most people have one upload target so just a button would be enough. When having two upload targets a dropdown list would suffice.

Btw, I love the upload speed using dropbox compared to the old Jing 👍

**Comment by vicnevicne** [comment]
I agree that it is strange to have two ways to manage targets but that was the way Jing did it (I just didn't have time to work on the "round wrench" button):
![image](https://user-images.githubusercontent.com/842233/88283737-50e8be80-ccec-11ea-8532-46c927f85f8a.png).
I'm keeping this open as a future enhancement.

**Comment by vicnevicne** [comment]
In 0.4.9, a new option is available to replace the upload menu by a specific button for each upload target
