### ISSUE TITLE
Ginj notification on export

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#19]
Feature request:  
on the Ginj notification it would be nice to have a link or button that opens the folder holding the saved snapshot the same way as it is when starting  'ginj.exe /create-i4j-log' it asks to open the saved explorer folder. The best thing about that is that it open the explorer windows with the saved file selected.

This comes in handy when saving a file you usually want to do something with it afterwards :)

**Comment by vicnevicne** [comment]
I agree that showing where the file is would be better. That is changed, at least for Windows, using a call to "explorer /select". I've attempted to use similar logic for macOS and Linux but no idea if it will work (but I guess it's not the biggest issue on those platforms :-))

**Comment by Creamers158** [comment]
Will wait for the next release and try it out 👍

**Comment by vicnevicne** [comment]
v0.3.9 is out :-). 
I'm closing this issue but don't hesitate to reopen in case it isn't fixed.
