### ISSUE TITLE
No image in history

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#25]
I notice that the history is not showing my latest created snapshots. 
When I create a snapshot that I copy or upload,it wont be visible in the program history.
Though I see the image in the C:\Users\User\.Ginj\history folder ?!

Any idea what is going on?

**Comment by vicnevicne** [comment]
There was a known bug in 0.4.0 that caused the history ordering to be wrong (latest images being lost in the middle), or even a crash preventing to open the history (issue #24 )
Did you update to 0.4.1 ? And is the issue still present ?
Thanks.

**Comment by Creamers158** [comment]
Yes I use 0.4.0, after updating to 0.4.1 my history is filled again.
