### ISSUE TITLE
Video captures only work on primary display

### ISSUE THREAD

**Issue by vicnevicne** [Ginj-capture/Ginj#28]
FFmpeg returns an error when given coordinates outside of the primary display. 
It probably requires a special handling for other displays.

**Comment by janborup** [comment]
Hi @vicnevicne 
Just testet Video on the 0.4.2 version, but the capture video does't work anymore.
Has the chain gone off somewhere ?
/ cheers

**Comment by vicnevicne** [comment]
Oops, there's a clear regression indeed. 
Can you confirm the symptoms: Video seems to be recording but when pressing "stop", it just closes and no "capture editing" window pops up, right ?
I'll have a look tomorrow.

**Comment by janborup** [comment]
Yes.. exactly 😎

Med venlig hilsen

Jan Borup Coyle

**Comment by vicnevicne** [comment]
v0.4.3 was just released and should fix that issue (and others).
Sorry for the inconvenience.

**Comment by janborup** [comment]
Check... Video Capture works again.. 😎👍

**Comment by vicnevicne** [comment]
Fixed in 0.4.4
