### ISSUE TITLE
Ging is stuck when it's copied a saved image

### ISSUE THREAD

**Issue by riverdiego** [Ginj-capture/Ginj#35]
Steps
1- Open a saved screenshot from the history
2- Press on the copy button

Actual:
Getting this a lot of time and then the copy is not saved in the clipboard. The Exporting overlay is never closed
![image](https://user-images.githubusercontent.com/22159796/119001123-14184300-b962-11eb-956d-b67a7f0f8c04.png)

Expected: 
The image is properly copied on the clipboard

**Comment by vicnevicne** [comment]
Thanks for reporting the issue. A few questions:
- Can you confirm you used Ginj before (seeing the number of captures in your history, I guess so :-)) and did you encounter the issue only with the new version 0.4.5 or already before ?
- Is it 100% reproductible ? With all captures in your history or only some of them ?
I could not reproduce the issue with captures in the history.
However, I got the "Export window does not close" behaviour once when copying a new capture to the clipboard, but also could not reproduce the problem :-(

**Comment by riverdiego** [comment]
Hi, yes, i started using it from the beginning :) it's a really good tool, i think it's something related to the amount of pictures because i was also facing a similar issue with the previous version but less frequently than with the latest one. 
When it happens, i have to open the "Task Manager", kill it, and open it again. It happens after takes 4 or 5 screenshots (take the screenshot, add a draw and copy it within the clipboard)

**Comment by vicnevicne** [comment]
Hi, can you try with v0.4.6 (just released) ?
Hopefully the export popup window should not remain forever (and in case it does, you should now be able to close it)
all feedback is welcome.

**Comment by vicnevicne** [comment]
@riverdiego @DennisPolack 
Could you please tell me if you still encounter the "uncloseable windows" with 0.4.6 ?
Thanks

**Comment by riverdiego** [comment]
Hi @vicnevicne , i've been using it from its release with no issues, great release!! Thanks for all!!

**Comment by DennisPolack** [comment]
Hi Vicne,

 

It appears to have been fixed. Unable to reproduce error which was previously easy to repeat.

 

Thanks

Dennis
