### ISSUE TITLE
Would be great if the procedure remembered what Action you performed previously on opening.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#39]
I normally use the Text box first upon opening. The procedure very often defaults to the Arrow option.

**Comment by vicnevicne** [comment]
Yep, Arrow is the default currently.
I'm adding that request to the todo.md file

**Comment by DennisPolack** [comment]
Hi,

 

That will be great.

 

BWD

**Comment by vicnevicne** [comment]
Implemented in v0.4.9

**Comment by DennisPolack** [comment]
Thank you will monitor and advise of anything untoward happening.
