### ISSUE TITLE
Target Edits

### ISSUE THREAD

**Issue by infinitebizmedia** [Ginj-capture/Ginj#4]
When creating a Save target (because you cant seem to edit existing one) and I name it something other then "Save," it fails at saving the file. It seems to default to the java folder which fails access. rightfully so.

![2020-07-16_14-15-02](https://user-images.githubusercontent.com/26210871/87707319-ecb77f00-c76e-11ea-8c0f-8667edf1e347.png)

**Comment by janborup** [comment]
Hi @infinitebizmedia 

This is because your **C:\Program Files\Ginj** folder is restricted by system... and normally you cannot save in this folder.

Choose another folder and it will work smooth 👍 

![image](https://user-images.githubusercontent.com/6866443/87720926-f912fa80-c7b5-11ea-8988-43ed322fd5aa.png)

/ Cheers

**Comment by vicnevicne** [comment]
Yep, as @janborup says, Ginj does not run with administrator privilege by default, so it has no write access to C:\Program Files, C:\Windows , or other user's profiles.
If you really want to save your captures in Program Files (which I wouldn't advise), you can start Ginj as administrator:
- either once by right clicking the icon + "Run as administrator"
- or always, by right clicking the icon > Properties > Compatibility > Run this program as administrator. You'll be prompted for confirmation each time Ginj starts though.

Now I admit the error message could be a bit more explanatory :-)

**Comment by infinitebizmedia** [comment]
yes. i see what you are saying. closing.... but opening a new one different topic. WOW this is just like work..hahaha

**Comment by vicnevicne** [comment]
:-)
By the way, target editing is done. It will be in the next release, in a few hours or tomorrow.

**Comment by vicnevicne** [comment]
Released in v0.3.5
