### ISSUE TITLE
Dragging and Dropping does not work for me

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#41]
When I try to Drag and Drop a file (normally a Screen Shot) I get a very peculiar result which looks like a URL but does not open.
I probably do more than 5 Screen Shots a day and haven't experienced this problem before.

**Comment by vicnevicne** [comment]
Hi,
I'm sorry I don't understand that issue... :-(
The way I use Ginj never involves Drag and Drop... I select an area, annotate it, then export it (to clipboard / disk / online), then paste the result where I need it (e.g. paste the image from the clipboard to Word / paste the file path in an "Attach file" dialog / paste the URL in a forum post).
Can you be more specific about when in your workflow you use Drag and Drop ?
Can you also explain what you mean by "a result which looks like a URL but does not open" ?
A copy paste of that URL - or better yet, a screenshot ;-) - would probably help.
KR,
Vicne.

**Comment by DennisPolack** [comment]
Hi Vicne,

 

Sorry this was confusing – It had nothing to do with GINJ = I was trying to drag and drop a Screen Shot to Git Hub and had the problems mentioned.

 

Apologies

 

Best Wishes
Dennis Polack

 

   www.fishwisepro.com <http://www.fishwisepro.com/>

**Comment by DennisPolack** [comment]
Hi Vicne,

 

See 2 attached screenshots

 

 

Best Wishes
Dennis Polack

 

   www.fishwisepro.com <http://www.fishwisepro.com/>

**Comment by vicnevicne** [comment]
Hi,

As you replied by e-mail, no attachment reached Github
If you have difficulties dragging images to attach them to a Github issue, try clicking the "Attach files by dragging & dropping, selecting or pasting them", then you'll be able to browse and select your image file.
I'm going to close the issue right now as it's not a Ginj issue.

Vicne

**Comment by DennisPolack** [comment]
Hi Vicne,

 

Thank you for feedback

 

Dennis

**Comment by vicnevicne** [comment]
Hi Dennis,
Side-note:
Although Github supports commenting on an issue by simply replying to notification e-mails, it causes the full e-mail to be included in the issue, with signatures and the full mail chain. So I just edited your comments to clean them up ;-)
So If possible, I suggest you click on the "View on Github" link at the bottom e-mails so you can fill the github form and avoid posting uselessly long comments.
Kind regards,
Vincent

**Comment by DennisPolack** [comment]
I have found that although I have changed the target folder the save is done to the previously selected folder. I noticed this a few times but wondered if I had not selected the new folder correctly. I monitored carefully this time and it was definitely saved to the  wrong folder.

**Comment by DennisPolack** [comment]
On your orange yellow sun it would be good to add tool tips. I make it a point of doing this on all buttons and icons.

**Comment by vicnevicne** [comment]
Could you please open two separate issues for the above problems ? That makes it easier to process and close them one by one. Thanks :-)

**Comment by DennisPolack** [comment]
I thought I had made it into 2 issues - It certainly looks like 2 different messages. What is the difference between an Issue and a comment ?

**Comment by vicnevicne** [comment]
Well... are you using a PC/mac ? Issue vs Comment sounds quite self-explanatory.
An "issue" is a specific problem you report, One problem = one issue. You create a new issue by clicking the "New Issue" green button at the top right of the page. In the past, you successfully created issues #37 , #37 , #38 , #39 , etc.
A "comment" on the other hand is additional information, questions, answers or general progress related to a specific issue, that you type (as I currently do) in the box at the bottom of an issue and clicking the green "Comment" button at the bottom. Tour answer "I thought I had made it into 2 issues..." was a comment, but you posted that comment inside this issue, issue #41 which is related to Dragging and Dropping.
Hope it makes sense...

**Comment by DennisPolack** [comment]
![2021-06-14_09-16-04 A link on the Comment page to Issues might be a good idea](https://user-images.githubusercontent.com/68514033/121865100-deb30b00-ccfd-11eb-8d34-baa22b6e51a6.png)
 
This is what I get when I drag and drop one of your png's 
This is a comment

**Comment by DennisPolack** [comment]
Hi Vincent,

 

I am using 4 different computers all with Windows 10

 

Best Wishes

Dennis

**Comment by vicnevicne** [comment]
?
You seem to assume I am the owner of GitHub... :-)
Github hosts 100 000 000+ projects, and Ginj, my project, is just one of them.

When you open an issue (like this one or the previous ones), Github automatically notifies you by email if someone posts a comment on it (so you are probably receiving this message as one of the Github notifications).

At the bottom of those notification e-mails, the "View in Github" link sends you directly to the bottom of the page related to the issue you opened, You can then read those comments, and optionally reply by adding a new comment. But this is all related to that specific issue.
If you want to open a new - unrelated - issue, you have to scroll up to the top of the page and use the "New issue" button at the right.
Or if you want to see all open issues, scroll up to the top of the page and click on the word "issues" on the left.

Of course I have no way to change the way Github works, or the layout of its pages and notification e-mails...
