### ISSUE TITLE
It would be nice if GINJ accepted inverted commas. I am pretty sure that Jing did.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#53]
It would be nice if GINJ accepted inverted commas. I am pretty sure that Jing did.

**Comment by DennisPolack** [comment]
It would be nice if GINJ accepted inverted commas. I am pretty sure that Jing did.
I have tried using arrows >>Text<< it is cumbersome and doesn't mean the same as "Inverted Commas" (>>Inverted Commas<<)

**Comment by vicnevicne** [comment]
Mmmh, I admit I don't understand what you mean by "inverted commas"...
Do you mean quotes ? As far as I can tell, all are supported : 
![2021-12-16_22-51-39](https://user-images.githubusercontent.com/842233/146454438-ff7618da-30ba-4702-a0a4-bd748963d58f.png)
Now some of them are not available on all keyboards, but you can get them using copy/paste or (on Windows at least) by typing their codes, e.g. Alt 0171 and Alt 0187 for « »

In any case I don't think it really is a Ginj issue.

If you mean something else, just tell me...

Vicne

**Comment by DennisPolack** [comment]
Hi Vicne,

 

Yes, I was talking about double quotes. In previous version I could never save if there were double quotes in the text and have studiously avoided them ever since.

If it now works it will be wonderful. I will check when GINJ is working again.

 

Sorry I won’t bring up issues again that are already logged.  I felt that if you got the issue more than once and from more than one person you would be in a better

position to evaluate priorities.

 

Best Wishes

Dennis

**Comment by vicnevicne** [comment]
Err, maybe I didn't understand what you mean by "accept".
I thought you meant you weren't able to type double quotes in a text box.
Now I understand you meant using double quotes in the **name** of the capture under the image, and indeed that name is used as the default filename, which cannot contain double quotes on Windows:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

When looking at the log, Ginj indeed does not perform any "cleanup" on the capture name before passing it to the filename selection box, and that causes an error:
'''
Encountered an error while saving image as
'D:\TEMP\2021-12-18_23-02-21 "test".png'
Can't create an ImageOutputStream!
More info is available on the Java console
javax.imageio.IIOException: Can't create an ImageOutputStream!
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1551)
	at info.ginj.export.disk.DiskExporter.exportCapture(DiskExporter.java:240)
	at info.ginj.ui.CaptureEditingFrame.lambda$onExport$10(CaptureEditingFrame.java:642)
	at java.base/java.lang.Thread.run(Thread.java:832) 
'''
I'll add a "cleanup" phase to make sure forbidden characters are replaced before saving.

Thanks.

**Comment by DennisPolack** [comment]
Hi Vicne,

 

Thank you.

 

Yes, the problem was in copying part of the text which had double quotes in the Text box and pasting it into the filename. Because I got an error I assumed it was a GINJ error and didn’t look any further. Only after your message did I test and confirm that the double quotes in the filename were 

the problem. Thanks again,

Clearing that up will make it much nicer.

 

See note in red below.

 

Best Wishes
Dennis Polack

 

    <http://www.fishwisepro.com/> www.fishwisepro.com

**Comment by vicnevicne** [comment]
Hi Dennis,

Can you try the latest (0.4.8) version to see if it solves the issue ?

Also, please reply on the Github website and not by e-mail, because Github only imports basic text from e-mails (no attachments, no font color etc.)

Kind regards,
Vincent

**Comment by DennisPolack** [comment]
Hi Vicne, Thank you - Works perfectly now after restart.

Thanks again

Best Wishes for a Merry Christmas and a Healthy and Rewarding New Year.

**Comment by vicnevicne** [comment]
Thanks for reporting the issue, testing and confirming it's now OK.

Best wishes to you and your loved ones.
