### ISSUE TITLE
Multiple capture selection.  Feature requests and thank you!

### ISSUE THREAD

**Issue by qu0zz** [Ginj-capture/Ginj#59]
Thanks for producing this, it's saved my sanity. I had Jing which failed on me on April 1st (not funny) and I was unable to re-install. 
I stumbled across this - it's fantastic thank you!

**This is a later edit of this post** 
Points 2 to 4 have now been raised as separate issues (with some expansion/explanation).
Point 1 below, (multiple selection of captures) was released in verion x64_0_4_11 and I can confirm it works exactly as expected noting that there is also a useful warning dialogue before deletion which states how many files are selected. 
Thank you!

These aren't necessarily issues but suggestions. Apologies as I'm not sure if I should submit each issue separately.  (done)

1. The ability to select multiple files in the history window (using the Shift and Ctrl keys as is usual in windows) to enable multiple deletions at once.

_The following are covered in separate issues so you can ignore anything below this line._
2. I can't find a way to produce text with a transparent background? I first thought the multicolured boxes on the colour picker option under Colour/Custom was the way forward (the boxes don't do anything) but depite the top sample text appearing to show text on a clear background I couldn't achieve that.
3. It would be useful to be able to choose the line weighting of any drawn box. The default box outline is very heavy.
4. When saving captures to different directories you can't see from the history box where they are located. (Either mouseover info or a location dropdown next to The Date/Size/Name filters would be useful)
The most useful would be a transparent background for text, but I'm so happy at what you've produced none of the above are vital.
Thank you again.

**Comment by vicnevicne** [comment]
Hi qu0zz,
Thanks for the kind words :-)
If you don't mind, could you indeed copy/paste the 4 requests to separate github issues ?
Improvements to History - (1) and (4) - are rather clear to me.
(3) is also self explanatory although I'm not sure how to integrate that in the UI while remaining simple...
Regarding (2), the color picker is the standard Java Dialog for picking a single color, and the boxes at the bottom just show how that color would fit in different contexts, they are not interactive indeed. Currently, the color selection only acts on the foreground indeed.
KR,
Vicne

**Comment by vicnevicne** [comment]
Please just open separate issues for points 2 to 4.
I just released an update implementing (1) ;-)
Vicne

**Comment by qu0zz** [comment]
Thank you, will do.

**Comment by vicnevicne** [comment]
Fixed in 0.4.11
