### ISSUE TITLE
Fixed -initial release of 0.4.1.2 wouldn't run on Win 10 (Re-release solved thank you!)

### ISSUE THREAD

**Issue by qu0zz** [Ginj-capture/Ginj#63]
Windows 10 Home up to date
Installed 04.1.2 (update current install) and it won't run showing a  STARTUP ERROR as below
Java.lang.ClassNotFoundException: info.ginj.Ginj
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
I de-installed all (using windows Uninstall in Programs and Features, re-installed 04.1.2, which still errors then re-installed 04.1.1 into the same directory and 04.1.1 runs OK, 
Then renamed the User settings folder (- just in case -C:\Users\myname\Ginj) tried a clean install, still the same.
04.1.1 reinstalled again still good
Any ideas?

**Comment by vicnevicne** [comment]
Gosh, you have just updated in the timeframe where I had uploaded a broken release :-(

The release is now fixed but it won't update automatically.
Please just uninstall Ginj and re-install a fresh copy of the release. Nothing should be lost.

I only noticed the broken release 2 hours after uploading it. The reason seems to be a change in the way maven packages the jar, but I was so confident that I rushed the build without checking it first. Really sorry for that.

**Comment by qu0zz** [comment]
Ha Ha, just my luck. I installed in that 2 hours completely randomly! But all good now and I can confirm that by closing Ginj and as a test without uninstalling I installed 04.1.2 over 04.11 into same directory worked without issue, (no uninstall required).
Thanks and I confirm 04.1.2 works as intended and previous settings were not affected
(notwithstanding text background colour (and transparency less so) option would be good but it's still great as is -thank you!) 
(I hope that doesn't sound ungrateful it's not intended to be!)

**Comment by vicnevicne** [comment]
Great that it works. Sorry again.
I'm not sure about the "text background colour (and transparency less so) option would be good". 
You noticed transparency is implemented, right ? I had not understood you also had an interest in changing the background color,  but I can put it in the TODO list. Don't hesitate to open a dedicated issue about it in that case.

**Comment by qu0zz** [comment]
hi vicnevicne
thanks, yes I did see the transparency option, and it's excellently implemented.
Sorry if my comment wasn't clear, but as you picked up I was thinking about the (possible future) text background colour implementation (and less so the future possibility of variable transparency on that background, which I've now realised isn't viable in the current implementation, (as the text box is firmly married to a border),  so ignore that comment- apologies. 
Simplicity is the key...
