### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by goofygrin** [Ginj-capture/Ginj#8]
I didn't see adding hotkey support in the TODO list.  This was a huge reason I loved Jing - I mapped alt-P to grabbing a screenshot and my workflow for annotating things (everything!) was super fast.

**Comment by vicnevicne** [comment]
Hi and thanks for testing Ginj. "Implement global shortcut" is in the TODO list, but I agree it is misnamed ;-)
I will raise its priority, now I know what my next challenge is.

**Comment by janborup** [comment]
Hi @vicnevicne 

I small addendum... Please assign [ESC] for the "History window", and [ESC] for the "Edit image" window.

/Cheers

**Comment by vicnevicne** [comment]
Yep, it's already in the TODO list as well: "Close most frames with ESC (ex: History)"
Good to know I was on the right track ;-)

**Comment by raultakahashi** [comment]
I made a Github account just to say YES PLEASE.

The hotkey was the primary reason I used classic Jing.  

I love and appreciate you keeping the spirit alive with Ginj!

**Comment by vicnevicne** [comment]
Thanks for the kind words.
I'll be abroad for the next 2 weeks so expect a huge slowdown in releases - and I can't promise a release before that - but I'll be back ;-))

**Comment by vicnevicne** [comment]
Hmm just took a look at a way to do it but unfortunately Java does not propose it out of the box so I'll have to rely on libs connecting natively to the OS,
Seems https://github.com/tulskiy/jkeymaster is the way to go.
Or, if it doesn't work, the more heavy https://github.com/kwhat/jnativehook .

**Comment by vicnevicne** [comment]
Hotkey support is in v0.3.6. ;-)
Closing

**Comment by raultakahashi** [comment]
<3!!!!!!
